# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('server', models.CharField(max_length=50)),
                ('database', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('I', 'Initial'), ('P', 'Pending'), ('R', 'Resolved')], max_length=50)),
                ('feedback_type', models.CharField(choices=[('B', 'Bug'), ('S', 'Suggestion')], max_length=50)),
                ('priority', models.CharField(choices=[('N', 'None'), ('H', 'Hight'), ('M', 'Medium'), ('L', 'Low')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
