# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionsetting',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
