# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentSched',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pnr', models.CharField(blank=True, max_length=50)),
                ('airline', models.CharField(blank=True, max_length=50, null=True)),
                ('fligthno', models.CharField(blank=True, max_length=50, null=True)),
                ('origin', models.CharField(blank=True, max_length=50, null=True)),
                ('destination', models.CharField(blank=True, max_length=50, null=True)),
                ('departure', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival', models.CharField(blank=True, max_length=50, null=True)),
                ('status_list', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
