# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gds', '0003_auto_20180314_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentsched',
            name='departure_date',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
    ]
