# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gds', '0006_auto_20180314_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='ticketing_issu_date',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='tkt_number',
        ),
        migrations.AddField(
            model_name='passenger',
            name='traveler_of',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='ticketing_issu_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='tkt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='departure_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.RemoveField(
            model_name='travel',
            name='identication',
        ),
        migrations.AlterUniqueTogether(
            name='travel',
            unique_together=set([('pnr', 'passenger')]),
        ),
    ]
