# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-23 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gds', '0008_auto_20180315_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedchange',
            name='departure_date',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
    ]
