# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180312_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='reward_value',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
