# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180312_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
