# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20180312_1223'),
        ('crm', '0004_auto_20180312_1008'),
    ]

    operations = [
    ]
