# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20180312_1008'),
        ('crm', '0003_auto_20180312_1223'),
    ]

    operations = [
    ]
