# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_merge_20180313_1002'),
        ('crm', '0005_merge_20180312_1719'),
    ]

    operations = [
    ]
