# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_merge_20180313_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveler',
            name='traveler_of',
        ),
        migrations.DeleteModel(
            name='Traveler',
        ),
    ]
