# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20180316_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='dep_from_blackout',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='dep_until_blackout',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='issued_from_blackout',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='issued_until_blackout',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='owrt',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='ret_from_blackout',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='ret_until_blackout',
        ),
        migrations.AddField(
            model_name='contract',
            name='dep_blackout',
            field=models.CharField(blank=True, default='ANY', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='issued_blackout',
            field=models.CharField(blank=True, default='ANY', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ret_blackout',
            field=models.CharField(blank=True, default='ANY', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dropnet',
            name='owrt',
            field=models.CharField(blank=True, choices=[('OW', 'One way'), ('RT', 'Round trip'), ('AN', 'Any')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='markup',
            name='owrt',
            field=models.CharField(blank=True, choices=[('OW', 'One way'), ('RT', 'Round trip'), ('AN', 'Any')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='owrt',
            field=models.CharField(blank=True, choices=[('OW', 'One way'), ('RT', 'Round trip'), ('AN', 'Any')], max_length=2, null=True),
        ),
    ]
