# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-19 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20180318_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
