# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-23 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20180319_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate', to='crm.Affiliate'),
        ),
    ]
