# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_user_affiliate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='arc_no',
            field=models.CharField(blank=True, default='ANY', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='class_svc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='destination',
            field=models.CharField(blank=True, default='ANY', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='fare_basis',
            field=models.CharField(blank=True, default='ANY', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='origin',
            field=models.CharField(blank=True, default='ANY', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tkt_designator',
            field=models.CharField(blank=True, default='ANY', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tour_code',
            field=models.CharField(blank=True, default='ANY', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='via_points',
            field=models.CharField(blank=True, default='ANY', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='x_destination',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='x_origin',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='x_via_points',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='dropnet',
            name='dropnet_value',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exceptionairline',
            name='com_value',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exceptionairline',
            name='net_value',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exceptionairline',
            name='pub_value',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='markup',
            name='com',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='markup',
            name='net',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='markup',
            name='pub',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
