# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20180327_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='fax_2',
        ),
        migrations.AddField(
            model_name='communication',
            name='email_cc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
