# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-17 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20180403_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMarkup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_markup', to='crm.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_reward', to='crm.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='markup',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='customer',
        ),
        migrations.AddField(
            model_name='customerreward',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Reward'),
        ),
        migrations.AddField(
            model_name='customermarkup',
            name='markup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Markup'),
        ),
    ]
